version: '3'
services:
  spring-boot-temporal-client-application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - spring-boot-temporal-client-redis-db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      REDIS_DATABASE: ${REDIS_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_TIMEOUT: ${REDIS_TIMEOUT}
      SERVER_PORT: ${SERVER_PORT}

  spring-boot-temporal-client-redis-db:
    container_name: spring-boot-temporal-client-redis-db
    image: eqalpha/keydb:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: keydb-server /etc/keydb/redis.conf --requirepass ${REDIS_PASSWORD}